### ISSUE TITLE
New website / docs UI chores

### ISSUE THREAD

**Issue by 0xjei** [semaphore-protocol/website#115]
**Todos**
- [ ] Remove `Docs` from `Learn` in the footer
- [ ] Update Semaphore logo
- [ ] Change Twitter to X
- [ ] ...
