### ISSUE TITLE
Integrate Algolia DocSearch

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/website#63]
**Tasks**:

- [x] Apply to the DocSearch program (https://docsearch.algolia.com/apply/)
- [x] Integrate Algolia into the website 
- [x] Trigger a new crawl

**Resources**:

* https://docusaurus.io/docs/search
