### ISSUE TITLE
Add warnings about possible side-effects in the contracts

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/website#66]
**Tasks**:

- [x] Reuse of identity commitments in groups
- [x] Merkle tree duration and creation dates
- [x] Absence of a check for the existence of members in the groups
- [x] Translate warnings to Spanish
